### ISSUE TITLE
Notes 31/3/2019

### ISSUE THREAD

**Issue by vinhtuanle** [vinhtuanle/tnmaker.net#1]
- Fix cố định các khung ( không di chuyển vị trí ) 11 text area
- truyền rect ( x ,y, w, h ), style (bold, italic, size )
- thêm custom font tiếng việt
- slide đậm nhạt

**Comment by ngoctigerstyle** [comment]
![image](https://user-images.githubusercontent.com/9814696/55687315-c0bb2480-5995-11e9-8eee-0591b996beb4.png)

**Comment by ngoctigerstyle** [comment]
next : 
+ Update style for each input element
